#!/usr/bin/env python3
"""Translate all SQL keywords in the autocomplete extension to Swiss German (Schwyzerdütsch)."""

import os
import re

# The grand Schwyzerdütsch SQL keyword mapping
# Trying to be authentically Züridütsch/Bärndütsch where possible
TRANSLATION = {
    # === Reserved keywords ===
    'ALL': 'ALLI',
    'ANALYSE': 'ANALYSIERE_ALT',
    'ANALYZE': 'ANALYSIERE',
    'AND': 'UND',
    'ANY': 'IRGENDÖPPIS',
    'ARRAY': 'REIHE',
    'AS': 'ALS',
    'ASC': 'UUFÄ',
    'ASYMMETRIC': 'ASYMMETRISCH',
    'BOTH': 'BEIDI',
    'CASE': 'FALL',
    'CAST': 'UMWANDLE',
    'CHECK': 'PRÜEFE',
    'COLLATE': 'SORTIERIG',
    'COLUMN': 'SPALTE',
    'CONSTRAINT': 'IISCHRÄNKIG',
    'CREATE': 'ERSTELLE',
    'DEFAULT': 'STANDARD',
    'DEFERRABLE': 'VERSCHIEBBAR',
    'DESC': 'ABÄ',
    'DESCRIBE': 'BESCHRIIBE',
    'DISTINCT': 'VERSCHIDE',
    'DO': 'MACH',
    'ELSE': 'SÜSCHT',
    'END': 'SCHLUSS',
    'EXCEPT': 'USSER',
    'FALSE': 'FALSCH',
    'FETCH': 'HOLE',
    'FOR': 'FÜR',
    'FOREIGN': 'FRÖMD',
    'FROM': 'VO',
    'GROUP': 'GRUPPE',
    'HAVING': 'HABEND',
    'QUALIFY': 'QUALIFIZIERE',
    'IN': 'I',
    'INITIALLY': 'AFANGS',
    'INTERSECT': 'SCHNITTMÄNGI',
    'INTO': 'INE',
    'LAMBDA': 'LAMBDA',
    'LATERAL': 'SIITLICH',
    'LEADING': 'VORANE',
    'LIMIT': 'BEGRÄNZE',
    'NOT': 'NID',
    'NULL': 'NÜT',
    'OFFSET': 'VERSATZ',
    'ON': 'UF',
    'ONLY': 'NUR',
    'OR': 'ODER',
    'ORDER': 'ORDNIG',
    'PIVOT': 'SCHWENKE',
    'PIVOT_WIDER': 'SCHWENKE_BREITER',
    'PIVOT_LONGER': 'SCHWENKE_LÄNGER',
    'PLACING': 'PLATZIERE',
    'PRIMARY': 'PRIMÄR',
    'REFERENCES': 'REFERÄNZE',
    'RETURNING': 'ZRUGGÄ',
    'SELECT': 'USWÄHLE',
    'SHOW': 'ZEIG',
    'SOME': 'ES_PAAR',
    'SUMMARIZE': 'ZÄMEFASSE',
    'SYMMETRIC': 'SYMMETRISCH',
    'TABLE': 'TABÄLLE',
    'THEN': 'DENN',
    'TO': 'ZU',
    'TRAILING': 'HINEDRA',
    'TRUE': 'WAHR',
    'UNION': 'VEREINIG',
    'UNIQUE': 'EINZIGARTIG',
    'UNPIVOT': 'ENTSCHWENKE',
    'USING': 'BRUUCHE',
    'VARIADIC': 'VARIADISCH',
    'WHEN': 'WÄNN',
    'WHERE': 'WO',
    'WINDOW': 'FÄNSCHTER',
    'WITH': 'MIT',

    # === Unreserved keywords ===
    'ABORT': 'ABBRÄCHE',
    'ABSOLUTE': 'ABSOLUT',
    'ACCESS': 'ZUEGRIFF',
    'ACTION': 'AKTION',
    'ADD': 'DEZUETUÄ',
    'ADMIN': 'VERWALTER',
    'AFTER': 'NACHHER',
    'AGGREGATE': 'AGGREGAT',
    'ALSO': 'AU',
    'ALTER': 'ÄNDERE',
    'ALWAYS': 'IMMER',
    'ASSERTION': 'BEHAUPTIG',
    'ASSIGNMENT': 'ZUEWISIG',
    'ATTACH': 'AHÄNKE',
    'ATTRIBUTE': 'EIGESCHAFT',
    'BACKWARD': 'ZRUGG',
    'BEFORE': 'VORHÄR',
    'BEGIN': 'AFANGE',
    'CACHE': 'ZWISCHESPEICHER',
    'CALL': 'AALÜTE',
    'CALLED': 'GRÜEFE',
    'CASCADE': 'KASKADE',
    'CASCADED': 'KASKADIERT',
    'CATALOG': 'KATALOG',
    'CENTURY': 'JAHRHUNDERT',
    'CENTURIES': 'JAHRHUNDERTE',
    'CHAIN': 'CHETTI',
    'CHARACTERISTICS': 'EIGESCHAFTE',
    'CHECKPOINT': 'SICHERIGSPUNKT',
    'CLASS': 'KLASS',
    'CLOSE': 'SCHLIESSE',
    'CLUSTER': 'HÜÜFE',
    'COMMENT': 'KOMMENTAR',
    'COMMENTS': 'KOMMENTÄR',
    'COMMIT': 'FESTLEGE',
    'COMMITTED': 'FESTGLEIT',
    'COMPRESSION': 'KOMPRESSION',
    'CONFIGURATION': 'KONFIGURATION',
    'CONFLICT': 'KONFLIKT',
    'CONNECTION': 'VERBINDIG',
    'CONSTRAINTS': 'IISCHRÄNKIGE',
    'CONTENT': 'INHALT',
    'CONTINUE': 'WIITERFAHRE',
    'CONVERSION': 'UMWANDLIG',
    'COPY': 'KOPIERE',
    'COST': 'CHOSCHTE',
    'CSV': 'CSV',
    'CUBE': 'WÜRFEL',
    'CURRENT': 'AKTUELL',
    'CURSOR': 'ZEIGER',
    'CYCLE': 'ZYKLUS',
    'DATA': 'DATE',
    'DATABASE': 'DATEBANK',
    'DAY': 'TAG',
    'DAYS': 'TÄG',
    'DEALLOCATE': 'FREGÄ',
    'DECADE': 'JAHRZÄHNT',
    'DECADES': 'JAHRZÄHNTE',
    'DECLARE': 'DEKLARIERE',
    'DEFAULTS': 'STANDARDS',
    'DEFERRED': 'VERSCHOBE',
    'DEFINER': 'DEFINIERER',
    'DELETE': 'LÖSCHE',
    'DELIMITER': 'TRÄNNZEICHE',
    'DELIMITERS': 'TRÄNNZEICHE_MEHRZAHL',
    'DEPENDS': 'ABHÄNGIG',
    'DETACH': 'ABHÄNKE',
    'DICTIONARY': 'WÖRTERBUECH',
    'DISABLE': 'DEAKTIVIERE',
    'DISCARD': 'VERWERFE',
    'DOCUMENT': 'DOKUMÄNT',
    'DOMAIN': 'DOMÄNE',
    'DOUBLE': 'DOPPELT',
    'DROP': 'ABESCHMISSE',
    'EACH': 'JEDES',
    'ENABLE': 'AKTIVIERE',
    'ENCODING': 'KODIERIG',
    'ENCRYPTED': 'VERSCHLÜSSLET',
    'ENUM': 'UFZÄHLIG',
    'ERROR': 'FÄHLER',
    'ESCAPE': 'FLUCHT',
    'EVENT': 'EREIGNIS',
    'EXCLUDE': 'USSCHLIESSE',
    'EXCLUDING': 'USSCHLIESSEND',
    'EXCLUSIVE': 'EXKLUSIV',
    'EXECUTE': 'USFÜHRE',
    'EXPLAIN': 'ERCHLÄRE',
    'EXPORT': 'EXPORTIERE',
    'EXPORT_STATE': 'EXPORTIERE_ZUESTAND',
    'EXTENSION': 'ERWIITERIG',
    'EXTENSIONS': 'ERWIITERIGE',
    'EXTERNAL': 'EXTERN',
    'FAMILY': 'FAMILIE',
    'FILTER': 'FILTER',
    'FIRST': 'ERSCHT',
    'FOLLOWING': 'FOLGEND',
    'FORCE': 'ZWINGE',
    'FORWARD': 'VORWÄRTS',
    'FUNCTION': 'FUNKTION',
    'FUNCTIONS': 'FUNKTIONE',
    'GLOBAL': 'GLOBAL',
    'GRANT': 'GEWÄHRE',
    'GRANTED': 'GEWÄHRT',
    'GROUPS': 'GRUPPENE',
    'HANDLER': 'BEHANDLER',
    'HEADER': 'CHOPFZIILE',
    'HOLD': 'BHALTE',
    'HOUR': 'STUND',
    'HOURS': 'STUNDE',
    'IDENTITY': 'IDENTITÄT',
    'IF': 'FALLS',
    'IGNORE': 'IGNORIERE',
    'IMMEDIATE': 'SOFORT',
    'IMMUTABLE': 'UNVERÄNDERLICH',
    'IMPLICIT': 'IMPLIZIT',
    'IMPORT': 'IMPORTIERE',
    'INCLUDE': 'IISCHLIESSE',
    'INCLUDING': 'IISCHLIESSEND',
    'INCREMENT': 'INKREMENT',
    'INDEX': 'VERZEICHNIS',
    'INDEXES': 'VERZEICHNISS',
    'INHERIT': 'ERBE',
    'INHERITS': 'ERBT',
    'INLINE': 'INLINE',
    'INPUT': 'IIGAB',
    'INSENSITIVE': 'UNEMPFINDLICH',
    'INSERT': 'INESETZE',
    'INSTALL': 'INSTALLIERE',
    'INSTEAD': 'STATTDESSE',
    'INVOKER': 'UFRUFER',
    'ISOLATION': 'ISOLATION',
    'JSON': 'JSON',
    'KEY': 'SCHLÜSSEL',
    'LABEL': 'ETIKETTE',
    'LANGUAGE': 'SPRACH',
    'LARGE': 'GROSS',
    'LAST': 'LETSCHT',
    'LEAKPROOF': 'DICHT',
    'LEVEL': 'STUFE',
    'LISTEN': 'LOSE',
    'LOAD': 'LADE',
    'LOCAL': 'LOKAL',
    'LOCATION': 'STANDORT',
    'LOCK': 'SPERRE',
    'LOCKED': 'GSPERRT',
    'LOGGED': 'PROTOKOLLIERT',
    'MACRO': 'MAKRO',
    'MAPPING': 'ABBILDIG',
    'MATCH': 'PASSE',
    'MATCHED': 'PASST',
    'MATERIALIZED': 'MATERIALISIERT',
    'MAXVALUE': 'MAXWÄRT',
    'MERGE': 'VERSCHMELZE',
    'METHOD': 'METHODE',
    'MICROSECOND': 'MIKROSEKUNDE',
    'MICROSECONDS': 'MIKROSEKUNDE_MZ',
    'MILLENNIA': 'JAHRTUSIGI',
    'MILLENNIUM': 'JAHRTUSIG',
    'MILLISECOND': 'MILLISEKUNDE',
    'MILLISECONDS': 'MILLISEKUNDE_MZ',
    'MINUTE': 'MINUTE',
    'MINUTES': 'MINUTE_MZ',
    'MINVALUE': 'MINWÄRT',
    'MODE': 'MODUS',
    'MONTH': 'MONET',
    'MONTHS': 'MÖNET',
    'MOVE': 'VERSCHIEBE',
    'NAME': 'NAME',
    'NAMES': 'NÄME',
    'NEW': 'NEU',
    'NEXT': 'NÖCHSCHT',
    'NO': 'KEI',
    'NOTHING': 'NÜÜT',
    'NOTIFY': 'BENACHRICHTIGE',
    'NOWAIT': 'NIDWARTE',
    'NULLS': 'NÜTWÄRT',
    'OBJECT': 'OBJÄKT',
    'OF': 'VOM',
    'OFF': 'UUS',
    'OIDS': 'OIDS',
    'OLD': 'ALT',
    'OPERATOR': 'OPERATOR',
    'OPTION': 'OPTION',
    'OPTIONS': 'OPTIONE',
    'ORDINALITY': 'ORDINALITÄT',
    'OTHERS': 'ANDERI',
    'OVER': 'ÜBER',
    'OVERRIDING': 'ÜBERSCHRIIBEND',
    'OWNED': 'BSITZT',
    'OWNER': 'BSITZER',
    'PARALLEL': 'PARALLEL',
    'PARSER': 'PARSER',
    'PARTIAL': 'TEILWIIS',
    'PARTITION': 'UFTEILIG',
    'PARTITIONED': 'UFTEILT',
    'PASSING': 'DUREGEBEND',
    'PASSWORD': 'PASSWORT',
    'PERCENT': 'PROZÄNT',
    'PERSISTENT': 'BESTÄNDIG',
    'PLANS': 'PLÄN',
    'POLICY': 'RICHTLINIE',
    'PRAGMA': 'PRAGMA',
    'PRECEDING': 'VORHÄRIG',
    'PREPARE': 'VORBEREITÄ',
    'PREPARED': 'VORBEREITET',
    'PRESERVE': 'UFBEWAHRE',
    'PRIOR': 'VORHERIG',
    'PRIVILEGES': 'RÄCHT',
    'PROCEDURAL': 'PROZEDURAL',
    'PROCEDURE': 'PROZEDUR',
    'PROGRAM': 'PROGRAMM',
    'PUBLICATION': 'VERÖFFENTLICHIG',
    'QUARTER': 'QUARTAL',
    'QUARTERS': 'QUARTÄL',
    'QUOTE': 'AFÜEHRIGSZEICHE',
    'RANGE': 'BEREICH',
    'READ': 'LÄSE',
    'REASSIGN': 'UMZUEWIISE',
    'RECHECK': 'NOMAL_PRÜEFE',
    'RECURSIVE': 'REKURSIV',
    'REF': 'REF',
    'REFERENCING': 'REFERENZIEREND',
    'REFRESH': 'UFFRISCHE',
    'REINDEX': 'NEU_INDEXIERE',
    'RELATIVE': 'RELATIV',
    'RELEASE': 'FRELAA',
    'RENAME': 'UMBENÄNNE',
    'REPEATABLE': 'WIDERHOOLBAR',
    'REPLACE': 'ERSETZE',
    'REPLICA': 'REPLIKAT',
    'RESET': 'ZRUGGSETZE',
    'RESPECT': 'RESPEKTIERE',
    'RESTART': 'NEU_STARTE',
    'RESTRICT': 'IISCHRÄNKE',
    'RETURNS': 'GIBT_ZRUGG',
    'REVOKE': 'ENTZIEH',
    'ROLE': 'ROLLE',
    'ROLLBACK': 'ZRUGGROLLE',
    'ROLLUP': 'UFROLLE',
    'ROWS': 'ZIILE',
    'RULE': 'REGLE',
    'SAMPLE': 'MÜSCHTERLI',
    'SAVEPOINT': 'SPEICHERPUNKT',
    'SCHEMA': 'SCHEMA',
    'SCHEMAS': 'SCHEMAS',
    'SCOPE': 'GÄLTIGSBEREICH',
    'SCROLL': 'SCROLLE',
    'SEARCH': 'SUECHE',
    'SECRET': 'GHEIMNIS',
    'SECOND': 'SEKUNDE',
    'SECONDS': 'SEKUNDE_MZ',
    'SECURITY': 'SICHERHEIT',
    'SEQUENCE': 'FOLG',
    'SEQUENCES': 'FOLGE',
    'SERIALIZABLE': 'SERIALISIERBAR',
    'SERVER': 'SERVER',
    'SESSION': 'SITZIG',
    'SET': 'SETZE',
    'SETS': 'MÄNGE',
    'SHARE': 'TEILE',
    'SIMPLE': 'EIFACH',
    'SKIP': 'ÜBERSPRINGE',
    'SNAPSHOT': 'MOMENTUFNAHM',
    'SORTED': 'SORTIERT',
    'SOURCE': 'QUÄLLE',
    'SQL': 'SQL',
    'STABLE': 'STABIL',
    'STANDALONE': 'ALLEISTEHEND',
    'START': 'STARTE',
    'STATEMENT': 'AAWISIG',
    'STATISTICS': 'STATISTIKE',
    'STDIN': 'STANDARDIIGAB',
    'STDOUT': 'STANDARDUSGAB',
    'STORAGE': 'SPEICHER',
    'STORED': 'GSPEICHERET',
    'STRICT': 'STRÄNG',
    'STRIP': 'ENTFERNE',
    'SUBSCRIPTION': 'ABONNEMÄNT',
    'SYSID': 'SYSID',
    'SYSTEM': 'SYSTEM',
    'TABLES': 'TABÄLLENE',
    'TABLESPACE': 'TABÄLLEBEREICH',
    'TARGET': 'ZIIL',
    'TEMP': 'PROVISORISCH',
    'TEMPLATE': 'VORLAGE',
    'TEMPORARY': 'VORÜBERGEHEND',
    'TEXT': 'TÄXT',
    'TIES': 'GLIICHSTÄND',
    'TRANSACTION': 'GSCHÄFT',
    'TRANSFORM': 'UMFORME',
    'TRIGGER': 'USLÖSER',
    'TRUNCATE': 'ABSCHNIIDE',
    'TRUSTED': 'VERTRAUT',
    'TYPE': 'TYP',
    'TYPES': 'TYPE',
    'UNBOUNDED': 'UNBEGRÄNZT',
    'UNCOMMITTED': 'NIDFESTGLEIT',
    'UNENCRYPTED': 'UNVERSCHLÜSSLET',
    'UNKNOWN': 'UNBEKANNT',
    'UNLISTEN': 'NÜMMELOSE',
    'UNLOGGED': 'NIDPROTOKOLLIERT',
    'UNTIL': 'BIS',
    'UPDATE': 'AKTUALISIERE',
    'USE': 'VERWÄNDE',
    'USER': 'BENUTZER',
    'VACUUM': 'STAUBSUUGE',
    'VALID': 'GÜLTIG',
    'VALIDATE': 'VALIDIERE',
    'VALIDATOR': 'VALIDIERER',
    'VALUE': 'WÄRT',
    'VARIABLE': 'VARIABLE',
    'VARYING': 'VARIIEREND',
    'VERSION': 'VERSION',
    'VIEW': 'AASICHT',
    'VIEWS': 'AASICHTE',
    'VIRTUAL': 'VIRTUELL',
    'VOLATILE': 'FLÜCHTIG',
    'WEEK': 'WUCHE',
    'WEEKS': 'WUCHE_MZ',
    'WHITESPACE': 'LEERZEICHE',
    'WITHIN': 'INNERHALB',
    'WITHOUT': 'OHNI',
    'WORK': 'ARBET',
    'WRAPPER': 'HÜLLE',
    'WRITE': 'SCHRIIBE',
    'XML': 'XML',
    'YEAR': 'JAHR',
    'YEARS': 'JAHRI',
    'YES': 'JA',
    'ZONE': 'ZONE',

    # === Column name keywords ===
    'BETWEEN': 'ZWÜSCHE',
    'BIGINT': 'GROSSZAHL',
    'BIT': 'BIT',
    'BOOLEAN': 'BOOLEAN',
    'CHAR': 'ZEICHE',
    'CHARACTER': 'BUECHSTABE',
    'COALESCE': 'ZÄMESCHMELZE',
    'COLUMNS': 'SPALTENE',
    'DEC': 'DEZ',
    'DECIMAL': 'DEZIMAL',
    'EXISTS': 'EXISTIERT',
    'EXTRACT': 'USENEH',
    'FLOAT': 'FLIESSKOMMA',
    'GENERATED': 'GENERIERT',
    'GROUPING': 'GRUPPIERIG',
    'GROUPING_ID': 'GRUPPIERIG_ID',
    'INOUT': 'IIUS',
    'INT': 'GANZ',
    'INTEGER': 'GANZZAHL',
    'INTERVAL': 'INTERVALL',
    'MAP': 'CHARTE',
    'NATIONAL': 'NATIONAL',
    'NCHAR': 'NZEICHE',
    'NONE': 'KEINS',
    'NULLIF': 'NÜTFALLS',
    'NUMERIC': 'NUMERISCH',
    'OUT': 'US',
    'OVERLAY': 'ÜBERLEGE',
    'POSITION': 'POSITION',
    'PRECISION': 'GNAUIGKEIT',
    'REAL': 'REELL',
    'ROW': 'ZIILE',
    'SETOF': 'MÄNGEVO',
    'SMALLINT': 'CHLIIZAHL',
    'STRUCT': 'STRUKTUR',
    'SUBSTRING': 'TEILZEICHECHETTI',
    'TIME': 'ZIIT',
    'TIMESTAMP': 'ZIITSCHTÄMPFEL',
    'TREAT': 'BEHANDLE',
    'TRIM': 'STUTZE',
    'TRY_CAST': 'PROBIER_UMWANDLE',
    'VALUES': 'WÄRT',
    'VARCHAR': 'ZEICHECHETTI',

    # XML stays as-is (proper nouns)
    'XMLATTRIBUTES': 'XMLEIGENSCHAFTE',
    'XMLCONCAT': 'XMLVERCHETTE',
    'XMLELEMENT': 'XMLELEMÄNT',
    'XMLEXISTS': 'XMLEXISTIERT',
    'XMLFOREST': 'XMLWALD',
    'XMLNAMESPACES': 'XMLNAMERUIM',
    'XMLPARSE': 'XMLPARSE',
    'XMLPI': 'XMLPI',
    'XMLROOT': 'XMLWURZE',
    'XMLSERIALIZE': 'XMLSERIALISIERE',
    'XMLTABLE': 'XMLTABÄLLE',

    # === Type/func name keywords ===
    'ASOF': 'ABEM',
    'AT': 'BI',
    'AUTHORIZATION': 'BEWILLIGUNG',
    'BINARY': 'BINÄR',
    'BY': 'NACH',
    'COLLATION': 'SORTIERIG',
    'CONCURRENTLY': 'GLIICHZIITIG',
    'CROSS': 'CHRÜZ',
    'FREEZE': 'IIFRIERE',
    'FULL': 'VOLL',
    'GLOB': 'MUSTER',
    'ILIKE': 'EGAL_WIE',
    'INNER': 'INNE',
    'IS': 'ISCH',
    'ISNULL': 'ISCHNÜT',
    'JOIN': 'VERBINDE',
    'LEFT': 'LINKS',
    'LIKE': 'WIE',
    'NATURAL': 'NATÜRLICH',
    'NOTNULL': 'ISCHNIDNÜT',
    'OUTER': 'USSE',
    'OVERLAPS': 'ÜBERLAPPT',
    'POSITIONAL': 'POSITIONAL',
    'RIGHT': 'RÄCHTS',
    'SEMI': 'HALB',
    'SIMILAR': 'ÄHNLICH',
    'TABLESAMPLE': 'TABÄLLEMÜSCHTERLI',
    'UNPACK': 'USPACKE',
    'VERBOSE': 'USFÜHRLICH',
    'ANTI': 'GÄGE',

    # === Extra keywords from gram files ===
    'ASCENDING': 'UFSTEIGEND',
    'DESCENDING': 'ABSTEIGEND',
    'GEOMETRY': 'GEOMETRIE',
    'VARIANT': 'VARIANTE',
}

# Post-process: replace umlauts with ASCII equivalents for case-insensitive matching compatibility
UMLAUT_MAP = {
    'Ä': 'AE',
    'Ö': 'OE',
    'Ü': 'UE',
    'ä': 'ae',
    'ö': 'oe',
    'ü': 'ue',
}

def asciify(s):
    for umlaut, replacement in UMLAUT_MAP.items():
        s = s.replace(umlaut, replacement)
    return s

# Apply ASCII-ification to all translation values
TRANSLATION = {k: asciify(v) for k, v in TRANSLATION.items()}


def translate_gram_file(filepath):
    """Replace 'KEYWORD' patterns in .gram files."""
    with open(filepath, 'r') as f:
        content = f.read()

    def replace_keyword(match):
        keyword = match.group(1)
        if keyword in TRANSLATION:
            return f"'{TRANSLATION[keyword]}'"
        return match.group(0)

    # Match single-quoted keywords: 'KEYWORD'
    new_content = re.sub(r"'([A-Z_]+)'", replace_keyword, content)

    with open(filepath, 'w') as f:
        f.write(new_content)

    return content != new_content


def translate_list_file(filepath):
    """Replace keywords in .list files (one per line, uppercase)."""
    with open(filepath, 'r') as f:
        lines = f.readlines()

    new_lines = []
    for line in lines:
        stripped = line.strip()
        if stripped and stripped in TRANSLATION:
            new_lines.append(TRANSLATION[stripped] + '\n')
        else:
            new_lines.append(line)

    with open(filepath, 'w') as f:
        f.writelines(new_lines)


def main():
    autocomplete_dir = os.path.join(os.path.dirname(__file__), 'extension', 'autocomplete')

    # Translate all .gram files
    gram_dir = os.path.join(autocomplete_dir, 'grammar', 'statements')
    changed = 0
    for filename in sorted(os.listdir(gram_dir)):
        if filename.endswith('.gram'):
            filepath = os.path.join(gram_dir, filename)
            if translate_gram_file(filepath):
                changed += 1
                print(f"  Übersetzt: {filename}")
    print(f"\n{changed} Grammatik-Dateie übersetzt!")

    # Translate all .list files
    keywords_dir = os.path.join(autocomplete_dir, 'grammar', 'keywords')
    for filename in sorted(os.listdir(keywords_dir)):
        if filename.endswith('.list'):
            filepath = os.path.join(keywords_dir, filename)
            translate_list_file(filepath)
            print(f"  Übersetzt: {filename}")
    print(f"\nSchlüsselwort-Lischte übersetzt!")

    # Also translate the inlined_grammar.gram if it exists
    inlined = os.path.join(autocomplete_dir, 'include', 'inlined_grammar.gram')
    if os.path.exists(inlined):
        translate_gram_file(inlined)
        print(f"\nInlined grammar au übersetzt!")

    print("\n🧀 Fertig! Jetzt no `python3 inline_grammar.py` laufe laa zum regeneriere.")


if __name__ == '__main__':
    main()
