# Marks all changed PR as draft
name: Draft on Synchronize
on:
  pull_request:
    types: [ synchronize, ready_for_review ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

jobs:
  mark-as-draft:
    name: Mark as draft
    if: github.event.pull_request.draft == false && github.event.pull_request.synchronize == true
    runs-on: ubuntu-latest
    steps:
      - name: Mark as draft
        uses: voiceflow/draft-pr@latest
        with:
          token: ${{ env.GH_TOKEN }}
