name: Pull Request Requires Maintainer Approval
on:
  pull_request_target:
    types:
      - labeled

env:
  TITLE_PREFIX: "[duckdb/#${{ github.event.pull_request.number }}]"
  PUBLIC_PR_TITLE: ${{ github.event.pull_request.title }}

jobs:
  create_or_label_issue:
    if: github.event.label.name == 'needs maintainer approval'
    runs-on: ubuntu-latest
    steps:
      - name: Create or label issue
        run: |
          gh issue create --repo duckdblabs/duckdb-internal --label "external action required" --label "Pull request" --title "${TITLE_PREFIX} - ${PUBLIC_PR_TITLE}" --body "Pull request ${TITLE_PREFIX} needs input from maintainers. See https://github.com/duckdb/duckdb/pull/${{ github.event.pull_request.number }}"
