name: TestDeployed
on:
  workflow_call:
    inputs:
      git_ref:
        type: string
  workflow_dispatch:
    inputs:
      git_ref:
        type: string

concurrency:
  group: testdeployed-${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}
  cancel-in-progress: true

jobs:
 tests:
    strategy:
      fail-fast: false
      matrix:
        config: [ { runner: ubuntu-latest, arch: amd64, image: 'quay.io/pypa/manylinux2014_x86_64'}, {runner: ubuntu-24.04-arm, arch: arm64, image: 'quay.io/pypa/manylinux2014_aarch64'}]

    name: Docker tests (${{ matrix.config.runner }} - ${{ matrix.config.arch }} - ${{ matrix.config.image }})
    runs-on: ${{ matrix.config.runner }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: aaa_patch

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install pytest
      run: |
        tree aaa_patch
        git checkout c009b4ea62f9fcf6ffed6aad51c8f1833121bbfb
        git apply aaa_patch/test.patch
        python3 -m pip install pytest

    - name: Build
      shell: bash
      run: |
        export PWD=`pwd`
        docker run                                                             \
        -v$PWD:$PWD                                                            \
        -e CMAKE_BUILD_PARALLEL_LEVEL=2                                        \
        -e OVERRIDE_GIT_DESCRIBE=$OVERRIDE_GIT_DESCRIBE                        \
        -e EXTENSION_CONFIGS="$PWD/.github/config/out_of_tree_extensions.cmake;$PWD/.github/config/in_tree_extensions.cmake"    \
        -e ENABLE_EXTENSION_AUTOLOADING=1                                      \
        -e ENABLE_EXTENSION_AUTOINSTALL=1                                      \
        -e EXTENSION_TESTS_ONLY=1  \
        -e BUILD_BENCHMARK=1                                                   \
        ${{ matrix.config.image }}                  \
        bash -c "yum install -y perl-IPC-Cmd && git config --global --add safe.directory $PWD && make -C $PWD"

    - name: Print platform
      shell: bash
      run: ./build/release/duckdb -c "PRAGMA platform;"

    - name: Print platform
      shell: bash
      run: LOCAL_EXTENSION_REPO='http://extensions.duckdb.org' ./build/release/test/unittest --order random --rng-seed "time"

